import type { Metadata } from "next";
import { Geist, Geist_Mono, Instrument_Serif } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Providers from "./Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const instrumentSerif = Instrument_Serif({
  weight: ['400'], // Instrument Serif only has Regular (400) and Italic (400-italic)
  subsets: ['latin'],
  display: 'swap', // This is good for performance
  variable: "--font-instrument", // Optional: Define a CSS variable for Tailwind/global use
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} ${instrumentSerif.variable} antialiased`}
      > 
         <Navbar />
         <Providers>
          <div className=" flex flex-col justify-center items-center">
            {children}
          </div>
         </Providers>

        {/* <ChatInput /> */}
      </body>
    </html>
  );
}
